[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "netlens"
version = "0.1.0"
description = "NetLens CLI and utilities"
requires-python = ">=3.9"
dependencies = []

[project.scripts]
netlens = "apps.cli.main:main"

